name: Build and Push

on:
  push:
    branches:
      - arch-neutron
  schedule:
      # Every Saturday at 1:30AM UTC
      - cron: "30 01 * * 6"
  workflow_dispatch:
   
env:
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_NAME: ${{ secrets.USER_NAME }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Building the Image
        run: |
          docker build -f Dockerfile . -t atomxorg/arch-linux:kernel
          echo "$PASSWORD" | docker login -u "atomxorg" --password-stdin
      - name: Pushing the Image
        run: |
          docker push atomxorg/arch-linux:kernel
